# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-02 06:10
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, max_length=40, validators=[blog.models.lnglat_validator]),
        ),
    ]
